import {
  Archive,
  ArrowLeftRight,
  CalendarClock,
  CircleDollarSign,
  Goal,
  Landmark,
  LayoutDashboard,
  LogOut,
  PiggyBank,
  Rocket,
  Shapes,
  Upload,
  UserRound,
  Users,
  Vault,
  WalletCards,
} from 'lucide-react';

export const moduleRegistry = {
  dashboard: {
    key: 'dashboard',
    path: '/',
    label: 'Dashboard',
    shortLabel: 'Dashboard',
    group: 'overview',
    icon: LayoutDashboard,
    status: 'live',
    description: 'Resumo financeiro, alertas, agenda e score semanal.',
  },
  accounts: {
    key: 'accounts',
    path: '/accounts',
    label: 'Contas',
    shortLabel: 'Contas',
    group: 'finance',
    icon: WalletCards,
    status: 'live',
    description: 'Cadastro e status das contas financeiras do usuario.',
  },
  boxes: {
    key: 'boxes',
    path: '/boxes',
    label: 'Caixas',
    shortLabel: 'Caixas',
    group: 'finance',
    icon: Vault,
    status: 'live',
    description: 'Organize reservas, saldos dedicados e objetivos do caixa.',
  },
  categories: {
    key: 'categories',
    path: '/categories',
    label: 'Categorias',
    shortLabel: 'Categorias',
    group: 'finance',
    icon: Shapes,
    status: 'live',
    description: 'Classifique receitas e despesas com mais clareza.',
  },
  transactions: {
    key: 'transactions',
    path: '/transactions',
    label: 'Transacoes',
    shortLabel: 'Receitas/Despesas',
    group: 'finance',
    icon: ArrowLeftRight,
    status: 'live',
    description: 'Receitas e despesas consolidadas em uma experiencia unica.',
  },
  withdrawals: {
    key: 'withdrawals',
    path: '/withdrawals',
    label: 'Retiradas',
    shortLabel: 'Retiradas',
    group: 'finance',
    icon: CircleDollarSign,
    status: 'live',
    description: 'Retiradas do socio registradas e geridas na mesma experiencia.',
  },
  debts: {
    key: 'debts',
    path: '/debts',
    label: 'Dividas',
    shortLabel: 'Dividas',
    group: 'finance',
    icon: Landmark,
    status: 'live',
    description: 'Dividas parceladas, pagamentos, estornos e exclusoes condicionadas.',
  },
  budgets: {
    key: 'budgets',
    path: '/budgets',
    label: 'Orcamentos',
    shortLabel: 'Orcamentos',
    group: 'planning',
    icon: PiggyBank,
    status: 'live',
    description: 'Limites mensais por categoria com manutencao direta na interface.',
  },
  goals: {
    key: 'goals',
    path: '/goals',
    label: 'Metas',
    shortLabel: 'Metas',
    group: 'planning',
    icon: Goal,
    status: 'live',
    description: 'Metas financeiras com progresso, ajuste e acompanhamento continuo.',
  },
  targets: {
    key: 'targets',
    path: '/targets',
    label: 'Alvos e Execucao',
    shortLabel: 'Alvos e Execucao',
    group: 'planning',
    icon: Rocket,
    status: 'live',
    description: 'Acompanhe prioridades, avancos e proximas acoes do plano.',
  },
  agenda: {
    key: 'agenda',
    path: '/agenda',
    label: 'Agenda',
    shortLabel: 'Agenda',
    group: 'operations',
    icon: CalendarClock,
    status: 'live',
    description: 'Veja o que pede atencao hoje e nos proximos dias.',
  },
  imports: {
    key: 'imports',
    path: '/imports',
    label: 'Importacao',
    shortLabel: 'Importacao',
    group: 'operations',
    icon: Upload,
    status: 'live',
    description: 'Upload manual e fila OFX operando dentro do proprio modulo.',
  },
  reports: {
    key: 'reports',
    path: '/reports',
    label: 'Relatorios',
    shortLabel: 'Relatorios',
    group: 'analysis',
    icon: Archive,
    status: 'live',
    description: 'Relatorios consolidados com filtros e resultado liquido do periodo.',
  },
  profile: {
    key: 'profile',
    path: '/profile',
    label: 'Meu acesso',
    shortLabel: 'Meu acesso',
    group: 'account',
    icon: UserRound,
    status: 'live',
    description: 'Dados pessoais, senha e preferencias da central de alertas.',
  },
  users: {
    key: 'users',
    path: '/users',
    label: 'Usuarios',
    shortLabel: 'Usuarios',
    group: 'admin',
    icon: Users,
    status: 'live',
    description: 'Gerencie acessos, perfis, status e visualizacao administrativa.',
    adminOnly: true,
  },
  logout: {
    key: 'logout',
    path: '/logout',
    label: 'Sair',
    shortLabel: 'Sair',
    group: 'account',
    icon: LogOut,
    status: 'action',
    description: 'Encerrar sua sessao com seguranca.',
  },
};

export const menuGroups = [
  { key: 'overview', label: 'Visao geral' },
  { key: 'finance', label: 'Financeiro' },
  { key: 'planning', label: 'Planejamento' },
  { key: 'operations', label: 'Operacao' },
  { key: 'analysis', label: 'Analise' },
  { key: 'account', label: 'Conta' },
  { key: 'admin', label: 'Admin' },
];

export function getNavigationGroups({ isAdmin = false } = {}) {
  return menuGroups
    .map((group) => ({
      ...group,
      items: Object.values(moduleRegistry).filter((item) => {
        if (item.group !== group.key) {
          return false;
        }

        if (item.adminOnly && !isAdmin) {
          return false;
        }

        return true;
      }),
    }))
    .filter((group) => group.items.length > 0);
}
